#!/bin/bash
#SBATCH   --partition=main
#SBATCH   --job-name=??
#SBATCH   -n 1 
#SBATCH   --mem=140G
#SBATCH   --time=2:00:00
#SBATCH   --output=output.out
#SBATCH   --error=error.log
#SBATCH   --mail-user=kai.zhang3@rutgers.edu
#SBATCH   --mail-type=BEGIN,END,FAIL
#SBATCH   --requeue
#SBATCH   --export=ALL

#blockMesh
#topoSet; refineMesh -overwrite;
#topoSet; refineMesh -overwrite;
#topoSet; refineMesh -overwrite;
decomposePar
